---
title: "03 Data Wrangling"
author: "Muhammad Affan Qamar"
date: "2021-05-11"
output:
 html_document:
    theme: cosmo
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 4
    #code_folding: hide
---

```{css, echo=FALSE}
body {
  color: black;
  background-color: #cde5e6;
  background-position: center top;
    background-size: cover;
    background-repeat: no-repeat;
  font-family:'Open Sans',sans-serif;
}
.list-group-item, .list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
  color: black;
  background-color: #a0f26d;
  border-color: #black;
  border-width: 6px;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

Last compiled: `r Sys.Date()`

# Data Science at TUHH ------------------------------------------------------

# Data Wrangling Challenges

### Import Libraries

```{r t2p1, fig.height=7, fig.width=10, message=FALSE}
library(tidyverse)
library(vroom)
library(data.table)
library(lubridate)
library(tictoc)
library(wesanderson)
library(jsonlite)
library(readxl)
library(DT)
library(yaml)
library(purrr)
library(dplyr)
library(DT)
library(RSQLite)
library(httr)
library(xopen)

```

# Part 1: Top Patents
10 US companies with the most assigned/granted patents.

```{r}
col_types <- list(
  id = col_character(),
  type = col_character(),
  number = col_character(),
  country = col_character(),
  date = col_date("%Y-%m-%d"),
  abstract = col_character(),
  title = col_character(),
  kind = col_character(),
  num_claims = col_double(),
  filename = col_character(),
  withdrawn = col_double()
)
```

```{r}
old_dir <- getwd()
setwd("C:/Users/Muhammad Affan Qamar/Documents/GitHub/bdsc-affan1947/Patent_data_reduced")
patent_tb1 <- vroom(
  file       = 'patent.tsv',
  delim      = "\t",
  col_types  = col_types,
  na         = c("", "NA", "NULL")
  )

assignee_tb1 <- vroom(
            file       = 'assignee.tsv', 
            delim      = "\t", 
            col_types  = col_types,
            na         = c("", "NA", "NULL")
        )

patent_assignee_tb1 <- vroom(
            file       = 'patent_assignee.tsv', 
            delim      = "\t", 
            col_types  = col_types,
            na         = c("", "NA", "NULL"))

uspc_tb1 <- vroom(
            file       = 'uspc.tsv', 
            delim      = "\t", 
            col_types  = col_types,
            na         = c("", "NA", "NULL")) %>%
            transform(patent_id = as.character(patent_id))


setwd(old_dir)

# Combine all of the databases into one large table;
wrangled <- assignee_tb1 %>%
            left_join(patent_assignee_tb1, by = c("id" = "assignee_id")) %>%
            left_join(patent_tb1, by = c("patent_id" = "id")) %>%
            left_join(uspc_tb1, by = "patent_id")

# Get the Organizations with the most patents using table() and sort()
tops <- sort(table(wrangled$organization), decreasing = T)[1:100] %>%
          as.data.frame() %>%
          mutate(Var1 = Var1 %>% str_to_title())


color <- toString(wes_palette("Darjeeling1", 4, type="discrete")[4])
longString = paste("$(this.api().table().header()).css({'color':'#010101', 'background-color' : '", color, "'});")

datatable(tops, class = 'cell-border stripe', 
          rownames = FALSE,
          colnames = c('Organization', 'Number of Patents (2014)'),
          options = list( initComplete = JS( "function(settings, json) {",longString,"}")))
```
# Part 2: The most granted patents in August 2014
```{r}

# Relevant data from the main database
wrangled_aug <- wrangled %>% 
                 select(organization, date) %>%
                
                 filter(date >= "2014-08-01" & date <= "2014-08-31")

Augusttop <- sort(table(wrangled_aug$organization), decreasing=T)[1:100] %>%
              as.data.frame() %>%
              mutate(Var1 = Var1 %>% str_to_title())


color <- toString(wes_palette("Darjeeling1", 4, type="discrete")[4])
longString = paste("$(this.api().table().header()).css({'color':'#010101', 'background-color' : '", color, "'});")

datatable(Augusttop, class = 'cell-border stripe', 
          rownames = FALSE,
          colnames = c('Organization', 'Number of Patents (Aug 2014'),
          options = list(initComplete = JS("function(settings, json) {",longString,"}")))

```

Done !!!